# Generated by Django 2.2.1 on 2019-05-18 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BibleChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(blank=False, null=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.BibleBook')),
            ],
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(blank=False, null=False)),
                ('text', models.CharField(max_length=700)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.BibleChapter')),
            ],
        ),
    ]
