# Generated by Django 2.2.1 on 2019-05-18 10:59
from django.db import migrations
import json
from bible.utils import ar_book_name


def populate_books(apps, schema_editor):
    BibleBook = apps.get_model('bible', 'BibleBook')
    BibleChapter = apps.get_model('bible', 'BibleChapter')
    BibleVerse = apps.get_model('bible', 'BibleVerse')

    with open('bible/data/ar_svd.json', mode='r', encoding='utf-8-sig') as ar_svd:
        ar_svd_data = json.load(ar_svd)

        for _, book in enumerate(ar_svd_data):
            book['ar_book'] = ar_book_name[book['name']]

            book_record = BibleBook()
            book_record.name = book['ar_book']
            book_record.save()

            for chapter_index, chapter in enumerate(book['chapters']):

                chapter_record = BibleChapter()
                chapter_record.index = chapter_index + 1
                chapter_record.book = book_record
                chapter_record.save()

                for verse_index, verse in enumerate(chapter):

                    verse_record = BibleVerse()
                    verse_record.index = verse_index + 1
                    verse_record.chapter = chapter_record
                    # verse_record.text = index_to_superscript(
                    #     verse_index + 1) + verse
                    verse_record.text = verse
                    verse_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_books),
    ]
