# Generated by Django 2.2.1 on 2019-05-18 10:59
from django.db import migrations
import json

ar_book_name = {
    'Genesis': 'تكوين',
    'Exodus': 'خروج',
    'Leviticus': 'لاويين',
    'Numbers': 'عدد',
    'Deuteronomy': 'تثنية',
    'Joshua': 'يشوع',
    'Judges': 'قضاة',
    'Ruth': 'راعوث',
    '1 Samuel': '1 صموئيل',
    '2 Samuel': '2 صموئيل',
    '1 Kings': '1 ملوك',
    '2 Kings': '2 ملوك',
    '1 Chronicles': '1 اخبار',
    '2 Chronicles': '2 اخبار',
    'Ezra': 'عزرا',
    'Nehemiah': 'نحميا',
    'Esther': 'استير',
    'Job': 'ايوب',
    'Psalms': 'مزامير',
    'Proverbs': 'امثال',
    'Ecclesiastes': 'جامعة',

    'Song of Songs': 'نشيد الانشاد',
    'Song of Solomon': 'نشيد الانشاد',

    'Isaiah': 'اشعياء',
    'Jeremiah': 'ارميا',
    'Lamentations': 'مراثي',
    'Ezekiel': 'حزقيال',
    'Daniel': 'دانيال',
    'Hosea': 'هوشع',
    'Joel': 'يوئيل',
    'Amos': 'عاموس',
    'Obadiah': 'عوبديا',
    'Jonah': 'يونان',
    'Micah': 'ميخا',
    'Nahum': 'ناحوم',
    'Habakkuk': 'حبقوق',
    'Zephaniah': 'صفنيا',
    'Haggai': 'حجى',
    'Zechariah': 'زكريا',
    'Malachi': 'ملاخي',
    'Matthew': 'متى',
    'Mark': 'مرقس',
    'Luke': 'لوقا',
    'John': 'يوحنا',
    'Acts': 'اعمال',
    'Romans': 'رومية',
    '1 Corinthians': '1 كورنثوس',
    '2 Corinthians': '2 كورنثوس',
    'Galatians': 'غلاطية',
    'Ephesians': 'افسس',
    'Philippians': 'فيلبي',
    'Colossians': 'كولوسي',
    '1 Thessalonians': '1 تسالونيكي',
    '2 Thessalonians': '2 تسالونيكي',
    '1 Timothy': '1 تيموثاوس',
    '2 Timothy': '2 تيموثاوس',
    'Titus': 'تيطس',
    'Philemon': 'فليمون',
    'Hebrews': 'عبرانيين',
    'James': 'يعقوب',
    '1 Peter': '1 بطرس',
    '2 Peter': '2 بطرس',
    '1 John': '1 يوحنا',
    '2 John': '2 يوحنا',
    '3 John': '3 يوحنا',
    'Jude': 'يهوذا',
    'Revelation': 'رؤيا',
}

superscript_map = {
    0: '\u2070',
    1: '\u00B9',
    2: '\u00B2',
    3: '\u00B3',
    4: '\u2074',
    5: '\u2075',
    6: '\u2076',
    7: '\u2077',
    8: '\u2078',
    9: '\u2079',
}


def index_to_superscript(index):
    result = ''
    while index > 0:
        result = superscript_map[index % 10] + result
        index //= 10
    return result


def populate_books(apps, schema_editor):
    BibleBook = apps.get_model('bible', 'BibleBook')
    BibleChapter = apps.get_model('bible', 'BibleChapter')
    BibleVerse = apps.get_model('bible', 'BibleVerse')

    with open('bible/data/ar_svd.json', mode='r', encoding='utf-8-sig') as ar_svd:
        ar_svd_data = json.load(ar_svd)

        for _, book in enumerate(ar_svd_data):
            book['ar_book'] = ar_book_name[book['name']]

            book_record = BibleBook()
            book_record.name = book['ar_book']
            book_record.save()

            for chapter_index, chapter in enumerate(book['chapters']):

                chapter_record = BibleChapter()
                chapter_record.index = chapter_index + 1
                chapter_record.book = book_record
                chapter_record.save()

                for verse_index, verse in enumerate(chapter):

                    verse_record = BibleVerse()
                    verse_record.index = verse_index + 1
                    verse_record.chapter = chapter_record
                    # verse_record.text = index_to_superscript(
                    #     verse_index + 1) + verse
                    verse_record.text = verse
                    verse_record.save()


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_books),
    ]
