# Generated by Django 2.2.1 on 2019-05-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0002_populate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='biblechapter',
            options={'ordering': ['book', 'index']},
        ),
        migrations.AlterModelOptions(
            name='bibleverse',
            options={'ordering': ['chapter', 'index']},
        ),
    ]
