# Generated by Django 2.2.1 on 2019-09-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0003_auto_20190518_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblechapter',
            name='index',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='bibleverse',
            name='index',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
