# Generated by Django 2.2.1 on 2019-09-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0004_auto_20190914_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='bibleverse',
            name='text_en',
            field=models.CharField(max_length=700, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='biblebook',
            name='name_en',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
    ]
