# Generated by Django 2.2.1 on 2019-07-12 09:33

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('challenges', '0001_initial'),
        ('bible', '0003_auto_20190518_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Group'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='start_verse',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='chapter', chained_model_field='chapter', on_delete=django.db.models.deletion.PROTECT, related_name='start_challenge', to='bible.BibleVerse'),
        ),
        migrations.AddField(
            model_name='answer',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.Challenge'),
        ),
    ]
