# Generated by Django 2.2.1 on 2020-01-03 09:08
from django.db import migrations, transaction
import re


def migrate_score(apps, schema_editor):
    Challenge = apps.get_model('challenges', 'Challenge')
    with transaction.atomic():
        for challenge in Challenge.objects.all():
            match = re.search('\s*(\d+)\s*', challenge.reward_name)
            if match is not None:
                challenge.reward_score = int(match.group())
                challenge.save()


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_challenge_reward_score'),
    ]

    operations = [
        migrations.RunPython(migrate_score),
    ]
