# Generated by Django 2.2.1 on 2019-09-21 07:59

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': 'Admin User', 'verbose_name_plural': 'Admin Users'},
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('letter', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.Group')),
            ],
        ),
        migrations.AddField(
            model_name='adminuser',
            name='service_class',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='service_group', chained_model_field='group', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Class'),
        ),
        migrations.AddField(
            model_name='user',
            name='group_class',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='group', chained_model_field='group', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Class'),
        ),
    ]
