# Generated by Django 2.2.1 on 2019-09-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190921_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6)]),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('group', 'grade', 'letter')},
        ),
    ]
