# Generated by Django 2.2.1 on 2019-10-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190921_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='class',
            name='letter',
        ),
    ]
