# Generated by Django 2.2.13 on 2022-09-29 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_populate_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='class',
            name='group',
        ),
        migrations.AlterField(
            model_name='adminuser',
            name='service_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_class', to='users.Class'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_class', to='users.Class'),
        ),
    ]
