# Generated by Django 2.2.13 on 2022-09-29 19:27

from django.db import migrations


def consolidate_classes(apps, schema_editor):
    User = apps.get_model('users', 'User')
    AdminUser = apps.get_model('users', 'AdminUser')
    Class = apps.get_model('users', 'Class')

    a_girls = Class.objects.create(name="A Girls")
    b_girls = Class.objects.create(name="B Girls")
    c_girls = Class.objects.create(name="C Girls")
    d_girls = Class.objects.create(name="D Girls")
    a_boys = Class.objects.create(name="A Boys")
    b_boys = Class.objects.create(name="B Boys")
    c_boys = Class.objects.create(name="C Boys")
    d_boys = Class.objects.create(name="D Boys")
    remaining_classes = [
        a_girls,
        b_girls,
        c_girls,
        d_girls,
        a_boys,
        b_boys,
        c_boys,
        d_boys,
    ]
    class_map = {}

    for c in remaining_classes:
        class_map[c.name] = c

    for user in User.objects.filter(group_class__isnull=False):
        if user.group_class.name in class_map:
            user.group_class = class_map[user.group_class.name]
            user.save()
        else:
            remaining_classes.append(user.group_class)

    for user in AdminUser.objects.filter(service_class__isnull=False):
        if user.service_class.name in class_map:
            user.service_class = class_map[user.service_class.name]
            user.save()

    class_ids = [c.id for c in remaining_classes]

    Class.objects.all().exclude(id__in=class_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220929_2217'),
    ]

    operations = [
        migrations.RunPython(consolidate_classes),
    ]
