# Generated by Django 2.2.10 on 2020-04-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.CharField(blank=True, choices=[('Issue', 'Issue'), ('Mood', 'Mood')], db_index=True, max_length=10, null=True),
        ),
    ]
